In [144]:
import pandas as pd

df = pd.read_csv("D:\Desktop\gmail-api-automation/artifacts/training_emails.csv")


<>:3: SyntaxWarning: invalid escape sequence '\D'
<>:3: SyntaxWarning: invalid escape sequence '\D'
C:\Users\amara\AppData\Local\Temp\ipykernel_19900\3330079628.py:3: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv("D:\Desktop\gmail-api-automation/artifacts/training_emails.csv")


In [145]:
df.head()

id                                               from  \
0  19407f49089741f0      Quora Digest <english-quora-digest@quora.com>   
1  194b3420600fb28b  Product Hunt Daily <hello@digest.producthunt.com>   
2  1924ea6d3edc5249                        Kaggle <noreply@kaggle.com>   
3  195ff039b6c376d3                      BSE ALERTS <info@bseindia.in>   
4  1938834def5580c7                    Alan Cowen <alan.cowen@hume.ai>   

                                             subject  \
0  If CTC is 9.5 LPA, then how much is the in-han...   
1                         😸 And the award goes to...   
2  📅 [Invitation] Google Cloud App Dev & Infrastr...   
3                         Funds / Securities Balance   
4  Voice Control by Hume – novel interpretability...   

                        date  \
0  2024-12-27 11:50:55+00:00   
1  2025-01-29 18:10:36+00:00   
2  2024-10-02 19:13:28+00:00   
3  2025-04-04 04:16:20+00:00   
4  2024-12-02 16:29:46+00:00   

                                             snippet  \
0  Greetings, It can vary for different companies...   
1  Announcing the 2024 Golden Kitty Award winners...   
2  Hi Varun reddy Amaravadhi, We&#39;re going to ...   
3  Dear Investor, With reference to BSE notices 2...   
4  We&#39;re introducing Voice Control, a novel i...   

                                                text        label  
0  quora.com If CTC is 9.5 LPA, then how much is ...  INFORMATION  
1  digest.producthunt.com 😸 And the award goes to...    PROMOTION  
2  kaggle.com 📅 [Invitation] Google Cloud App Dev...    PROMOTION  
3  bseindia.in Funds / Securities Balance Dear In...  INFORMATION  
4  hume.ai Voice Control by Hume – novel interpre...    PROMOTION

In [146]:
df.tail(5)

id                                               from  \
1795  193075eac5619e6b  king_of_pk_hari on Instagram <no-reply@mail.in...   
1796  199578374a25603c  "Superhuman – Zain Kahn" <superhuman@mail.join...   
1797  1919ca85398b7384  "Google Tips & Updates" <googlecommunityteam-n...   
1798  192af5105cfb4378  IndiaFirst Life Insurance <support@indiafirstl...   
1799  1989d303dcecdbb4               Codebasics Team <info@codebasics.io>   

                                                subject  \
1795  physics_curiosity_everyday, catch up on moment...   
1796                      New model creates 3D worlds 🌍   
1797       Explore how Google AI can help you every day   
1798    Your Life Insurance Service is now simplified !   
1799  Grateful for Your Participation in Resume Proj...   

                           date  \
1795  2024-11-07 16:04:10+00:00   
1796  2025-09-17 11:50:55+00:00   
1797  2024-08-29 05:42:42+00:00   
1798  2024-10-21 01:40:51+00:00   
1799  2025-08-12 07:30:16+00:00   

                                                snippet  \
1795  king_of_pk_hari, rikkiii.11 and others posted ...   
1796  ALSO: How to generate ad creatives with Nano B...   
1797  Get more done faster with these AI tips ‌ ‌ ‌ ...   
1798  ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ...   
1799  Thank You for Participating, Varun reddy Amara...   

                                                   text        label  
1795  mail.instagram.com physics_curiosity_everyday,...    PROMOTION  
1796  mail.joinsuperhuman.ai New model creates 3D wo...  INFORMATION  
1797  google.com Explore how Google AI can help you ...  INFORMATION  
1798  indiafirstlife.com Your Life Insurance Service...    IMPORTANT  
1799  codebasics.io Grateful for Your Participation ...  INFORMATION

In [147]:
X_text = df['text']
y = df['label']

In [148]:
X_text.shape

(1800,)

In [149]:
X_text.head()

0    quora.com If CTC is 9.5 LPA, then how much is ...
1    digest.producthunt.com 😸 And the award goes to...
2    kaggle.com 📅 [Invitation] Google Cloud App Dev...
3    bseindia.in Funds / Securities Balance Dear In...
4    hume.ai Voice Control by Hume – novel interpre...
Name: text, dtype: str

In [150]:
y.shape

(1800,)

In [151]:
y.head()

0    INFORMATION
1      PROMOTION
2      PROMOTION
3    INFORMATION
4      PROMOTION
Name: label, dtype: str

In [152]:
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    df["text"],
    df["label"],
    test_size=0.3,
    random_state=40,
    stratify=df["label"]
)


In [153]:
print(X_train_text.shape)
print(X_test_text.shape)
print(y_test.shape)
print(y_train.shape)

(1260,)
(540,)
(540,)
(1260,)


### cleaning and Vectorization

In [154]:
import re
#import nltk
#from nltk.corpus import stoprwords
from bs4 import BeautifulSoup

# TEXT CLEANING FUNCTION (EMAIL / NLP SAFE)
def clean_text(text):
    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # Remove HTML tags only if present
    if '<' in text and '>' in text:
        text = BeautifulSoup(text, 'html.parser').get_text()

    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)

    # Keep only letters and spaces
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# APPLY ONCE
X_train_text = X_train_text.apply(clean_text)
X_test_text = X_test_text.apply(clean_text)



In [155]:
X_train_text.shape

(1260,)

In [156]:
from sklearn.preprocessing import LabelEncoder
import joblib

lable_encoder = LabelEncoder()
y_train = lable_encoder.fit_transform(y_train)

# Transform test labels (NO FIT)
y_test = lable_encoder.transform(y_test)

# Save encoder
joblib.dump(lable_encoder, "D:\Desktop\gmail-api-automation/artifacts/label_encoder.pkl")

<>:11: SyntaxWarning: invalid escape sequence '\D'
<>:11: SyntaxWarning: invalid escape sequence '\D'
C:\Users\amara\AppData\Local\Temp\ipykernel_19900\3169516336.py:11: SyntaxWarning: invalid escape sequence '\D'
  joblib.dump(lable_encoder, "D:\Desktop\gmail-api-automation/artifacts/label_encoder.pkl")


['D:\\Desktop\\gmail-api-automation/artifacts/label_encoder.pkl']

In [157]:
import pandas as pd

counts_y_train = pd.Series(y_train).value_counts().sort_values()
print(counts_y_train)
print(f"total records used in training: {sum(counts_y_train)}")
counts_y_test = pd.Series(y_test).value_counts().sort_values()
print(counts_y_test)
print(f"total records used in training: {sum(counts_y_test)}")



0     25
4     83
2    197
1    328
3    627
Name: count, dtype: int64
total records used in training: 1260
0     10
4     36
2     84
1    141
3    269
Name: count, dtype: int64
total records used in training: 540


In [158]:
# 4. TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=25000,   # LIMIT THIS
    ngram_range=(1,2),
    sublinear_tf=True,
    min_df=2,
    max_df=0.95
)


In [159]:
X_train = vectorizer.fit_transform(X_train_text)
X_test  = vectorizer.transform(X_test_text)

In [160]:
print(X_train.shape)
print(X_test.shape)
print(y_test.shape)
print(y_train.shape)

(1260, 6593)
(540, 6593)
(540,)
(1260,)


In [161]:
import numpy as np
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

# Round to 2 decimal places
class_weight = {
    cls: round(weight, 2)
    for cls, weight in zip(classes, weights)
}

print(class_weight)


{np.int64(0): np.float64(10.08), np.int64(1): np.float64(0.77), np.int64(2): np.float64(1.28), np.int64(3): np.float64(0.4), np.int64(4): np.float64(3.04)}


In [162]:
class_weight = {
    0: 10.1,   # IMPORTANT - 25
    1: 0.8,   # INFORMATION - 328
    2: 1.28,   # OFFICIAL - 197
    3: 0.41,   # PROMOTION  - 627
    4: 3.04    # TRASH - 83
}

"""
0     25
4     83
2    197
1    328
3    627"""

'\n0     25\n4     83\n2    197\n1    328\n3    627'

In [163]:
# 5. Model
from sklearn.linear_model import LogisticRegression

Logistic_model = LogisticRegression(
    max_iter=3000,
    class_weight=class_weight,
    C=0.3,
    n_jobs=1              # IMPORTANT
)


Logistic_model.fit(X_train, y_train)

d:\Desktop\gmail-api-automation\gmailapi\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


LogisticRegression(C=0.3,
                   class_weight={0: 10.1, 1: 0.8, 2: 1.28, 3: 0.41, 4: 3.04},
                   max_iter=3000, n_jobs=1)

In [164]:
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, classification_report

y_pred = Logistic_model.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("classification report: \n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[ 10   0   0   0   0]
 [  2 115   4  19   1]
 [  1   0  82   1   0]
 [  7  24   6 230   2]
 [  0   1   0   3  32]]
Accuracy: 0.8685185185185185
classification report: 
               precision    recall  f1-score   support

           0       0.50      1.00      0.67        10
           1       0.82      0.82      0.82       141
           2       0.89      0.98      0.93        84
           3       0.91      0.86      0.88       269
           4       0.91      0.89      0.90        36

    accuracy                           0.87       540
   macro avg       0.81      0.91      0.84       540
weighted avg       0.88      0.87      0.87       540



In [165]:
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, classification_report

y_pred_train = Logistic_model.predict(X_train)

print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred_train))
print("Accuracy:", accuracy_score(y_train, y_pred_train))
print("classification report: \n", classification_report(y_train, y_pred_train))

Confusion Matrix:
 [[ 25   0   0   0   0]
 [  3 292   4  28   1]
 [  0   2 189   6   0]
 [  5  29  18 561  14]
 [  0   1   1   3  78]]
Accuracy: 0.9087301587301587
classification report: 
               precision    recall  f1-score   support

           0       0.76      1.00      0.86        25
           1       0.90      0.89      0.90       328
           2       0.89      0.96      0.92       197
           3       0.94      0.89      0.92       627
           4       0.84      0.94      0.89        83

    accuracy                           0.91      1260
   macro avg       0.87      0.94      0.90      1260
weighted avg       0.91      0.91      0.91      1260

